---
version: 2

project_name: a10r

before:
  hooks:
    - go mod download

release:
  prerelease: auto

env:
  - CGO_ENABLED=0

builds:
  - id: linux
    binary: a10r
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/wilfriedroset/a10r/cmd.version=v{{.Version}}
      - -X github.com/wilfriedroset/a10r/cmd.commit={{.Commit}}
      - -X github.com/wilfriedroset/a10r/cmd.date={{.Date}}

  - id: freebsd
    binary: a10r
    goos: [freebsd]
    goarch: [amd64, arm64]
    goarm: ["7"]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/wilfriedroset/a10r/cmd.version=v{{.Version}}
      - -X github.com/wilfriedroset/a10r/cmd.commit={{.Commit}}
      - -X github.com/wilfriedroset/a10r/cmd.date={{.Date}}

  - id: osx
    binary: a10r
    goos: [darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/wilfriedroset/a10r/cmd.version=v{{.Version}}
      - -X github.com/wilfriedroset/a10r/cmd.commit={{.Commit}}
      - -X github.com/wilfriedroset/a10r/cmd.date={{.Date}}

  - id: windows
    binary: a10r
    goos: [windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/wilfriedroset/a10r/cmd.version=v{{.Version}}
      - -X github.com/wilfriedroset/a10r/cmd.commit={{.Commit}}
      - -X github.com/wilfriedroset/a10r/cmd.date={{.Date}}

universal_binaries:
  - id: osx
    replace: true
    name_template: a10r

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - docs/**/*

checksum:
  name_template: checksums.sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "Merge pull request"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    maintainer: Wilfried Roset <Wilfried.roset@ovhcloud.com>
    homepage: https://github.com/wilfriedroset/a10r
    description: |
      Modern, fast, intuitive TUI for Prometheus Alertmanager and Grafana Mimir.
    license: Apache-2.0
    formats: [deb, rpm, apk]
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/a10r/copyright
        file_info:
          mode: 0644

sboms:
  - artifacts: archive
