// SPDX-License-Identifier: Apache-2.0

package tls

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// TestProbeCert_HTTPS_ServerCert exercises the happy path against an
// httptest TLS server. The server's leaf cert is autogenerated by
// httptest; ProbeCert returns it (NotAfter falls roughly one year
// out, so this test pins only the round-trip — the doctor checker's
// own tests cover the threshold logic).
func TestProbeCert_HTTPS_ServerCert(t *testing.T) {
	t.Parallel()

	srv := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	t.Cleanup(srv.Close)

	// httptest.NewTLSServer signs with an auto-generated cert; the
	// trustingDialer below pulls in the test server's RootCAs so the
	// handshake verifies. Without it, ProbeCert reports
	// x509.UnknownAuthority — covered below by the dial-failure path.
	pool := srv.Client().Transport.(*http.Transport).TLSClientConfig.RootCAs
	dialer := &poolDialer{pool: pool}

	cert, err := ProbeCert(t.Context(), srv.URL, dialer)
	require.NoError(t, err)
	require.NotNil(t, cert)
	require.True(t, cert.NotAfter.After(time.Now()),
		"the test server's auto-cert must not be already expired")
}

// TestProbeCert_NotHTTPS pins ErrNotHTTPS for the http:// scheme.
// Callers (the doctor check) translate the sentinel into a
// no-op SeverityOK row.
func TestProbeCert_NotHTTPS(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		url  string
	}{
		{name: "http", url: "http://am.internal:9093"},
		{name: "no scheme", url: "am.internal:9093"},
		{name: "ftp", url: "ftp://am.internal"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			_, err := ProbeCert(t.Context(), tc.url, nil)
			require.Error(t, err)
			require.ErrorIs(t, err, ErrNotHTTPS)
		})
	}
}

// TestProbeCert_DialFailure surfaces a dial failure as a wrapped
// error (not ErrNotHTTPS). Uses a stub dialer so the test does
// not depend on real network behaviour.
func TestProbeCert_DialFailure(t *testing.T) {
	t.Parallel()

	stub := &errorDialer{err: errors.New("connection refused")}
	_, err := ProbeCert(t.Context(), "https://nowhere.invalid", stub)
	require.Error(t, err)
	require.NotErrorIs(t, err, ErrNotHTTPS)
	require.Contains(t, err.Error(), "connection refused")
}

// TestProbeCert_MissingHost rejects URLs with no host portion. The
// doctor check should never feed such a URL — config validation
// runs first — but the helper guards anyway so a future caller
// passing a bare path surfaces a clear error.
func TestProbeCert_MissingHost(t *testing.T) {
	t.Parallel()
	_, err := ProbeCert(t.Context(), "https:///path", nil)
	require.Error(t, err)
	require.Contains(t, err.Error(), "no host")
}

// TestProbeCert_InvalidURL pins the parse-failure path. url.Parse
// rejects very few inputs, but a stray control char in the URL is
// one of them.
func TestProbeCert_InvalidURL(t *testing.T) {
	t.Parallel()
	_, err := ProbeCert(t.Context(), "https://exa\x7fmple.com", nil)
	require.Error(t, err)
	require.Contains(t, err.Error(), "parse url")
}

// errorDialer is a Dialer stub that always returns its preset
// error. Used to short-circuit the dial step in tests without
// touching the network.
type errorDialer struct{ err error }

func (e *errorDialer) DialContext(_ context.Context, _, _ string, _ *tls.Config) (*tls.Conn, error) {
	return nil, e.err
}

// poolDialer dials with the supplied RootCAs replacing the caller's
// (otherwise nil → system roots). Used to verify the auto-generated
// httptest cert without disabling verification entirely.
type poolDialer struct{ pool *x509.CertPool }

func (p *poolDialer) DialContext(ctx context.Context, network, addr string, cfg *tls.Config) (*tls.Conn, error) {
	merged := cfg.Clone()
	merged.RootCAs = p.pool
	d := tls.Dialer{Config: merged}
	conn, err := d.DialContext(ctx, network, addr)
	if err != nil {
		return nil, err
	}
	return conn.(*tls.Conn), nil
}
